CREATE TABLE USERS (
  ID NUMBER,
  CONSTRAINT USERS_PK PRIMARY KEY (ID),
  USER_NAME NVARCHAR2(100) NOT NULL,
  USER_PASSWORD NVARCHAR2(100) NOT NULL,
  COUNTRY NVARCHAR2(100) NOT NULL,
  USER_TYPE NVARCHAR2(50)
  );