CREATE TABLE ORDERS (
  ID NUMBER,
  CONSTRAINT ORDER_PK PRIMARY KEY (ID),
  USERS_ORDERED NUMBER,
  CONSTRAINT USERS_FK FOREIGN KEY (USERS_ORDERED) REFERENCES USERS (ID),
  ROOM NUMBER,
  CONSTRAINT ROOM_FK FOREIGN KEY (ROOM) REFERENCES ROOM (ID),
  DATE_FROM TIMESTAMP(6) WITH TIME ZONE,
  DATE_TO TIMESTAMP(6) WITH TIME ZONE,
  MONEY_PAID NUMBER(8,2) NOT NULL
  );