CREATE TABLE "FILE" (
ID NUMBER,
CONSTRAINT FILE_PK PRIMARY KEY (ID),
NAME NVARCHAR2(100),
FORMAT NVARCHAR2(50),
"SIZE" NUMBER,
STORAGE NUMBER,
CONSTRAINT STORAGE_FK FOREIGN KEY (STORAGE) REFERENCES STORAGE (ID)
);